### ISSUE TITLE
"index list out of range" error

### ISSUE THREAD

**Issue by paul1995tu** [euronion/trace#16] opened 2022-07-06 16:19 UTC
When running `snakemake -jall --restart-times 3 results/default/2030/hvdc-to-elec/ES-DE/results.csv`:

```
[Wed Jul  6 17:46:22 2022]
rule convert_fraunhofer:
    input: docu/Anhang-Studie-Wege-zu-einem-klimaneutralen-Energiesystem.pdf
    output: inputs/Fraunhofer_ISE_costs.csv, inputs/Fraunhofer_ISE_energy_prices.csv
    jobid: 1
    reason: Missing output files: inputs/Fraunhofer_ISE_energy_prices.csv, inputs/Fraunhofer_ISE_costs.csv
    resources: tmpdir=/tmp, mem=500

0
Traceback (most recent call last):
  File "/home/pirski/Diplomarbeit/projectz/technology-data/.snakemake/scripts/tmpzelaubzr.convert_pdf_fraunhofer_to_dataframe.py", line 33, in <module>
    clean_df[j-1] = clean_df[j-1].append(df_list[i])
IndexError: list index out of range


```

**Comment by euronion** [comment] 2022-07-08 09:40
That's weird. Did you modify the `technology-data` repository in some way?
If it was modified there might be bugs caused by the other repository.
If the modifications are of no relevance and happened unintentionally, you can download the repository (https://github.com/pypsa/technology-data) again and then the workflow should not trigger.

I'll see if I can reproduce the issue. If yes we'd probably need to report it upstream here: https://github.com/pypsa/technology-data

**Comment by euronion** [comment] 2022-07-08 13:33
Issues with that script from the upstream `technology-data` repository have been known for a year now. The script is actually broken and no longer part of the active repository. With the this commit https://github.com/euronion/trace/commit/4c8d67026213764c613a8dad47763c327b265527 the issue is addressed by removing the parallel `technology-data` repository and downloading the cost assumptions directly from source.

**Closed by euronion** 2022-07-08 13:33 UTC
